# Secrets configuration - keep this file private!
# This file will be merged with your main configuration
db:
    remote:
        username: kmy_userz
        password: supersecretpassword
        hostname: 'mysql.myhost.net'
        port: 3306
        database: my_database_name